theme: jekyll-theme-cayman
title: Voldy87 website
description: Projects, Apps, and many more..
google_analytics: UA-111922882-1
author: Andrea Orlandi
email: ing.orlandi.andrea@gmail.com
github: [metadata]
project_url: https://projects.voldy87.tk